### ISSUE TITLE
Is this repo still being maintained?

### ISSUE THREAD

**Issue by goetzk** [czue/django-wedding-website#12]
Hi Cory,
Thanks for opening your project, it will provide a solid base for what we're trying to do.

I see a number of unanswered issues and pull requests and wondered if you are maintaining this project still. If not we'll carry our changes and not make an effort to upstream them.

thanks,
Karl.

**Comment by czue** [comment]
Hi Karl,

I had my notification settings wrong :man_facepalming: . I am happy to still maintain this repo and will go through things now. Apologies for that!
