### ISSUE TITLE
+1?

### ISSUE THREAD

**Issue by dillwishlist** [czue/django-wedding-website#23]
Great project, I'm using it for my wedding website.  Is there a way to track +1s in the current code?

Thanks,
Alexander

**Comment by czue** [comment]
There's not explicitly. What we did for our wedding was just create `Guest`s named "Guest" attached to a `Party` with the person who you are giving the +1. It worked pretty well!

Let me know if that's sufficient for your use case.

**Comment by dillwishlist** [comment]
That was my initial thought, but I don't see any way to mark attendance on a guest by guest basis, only the whole party.  Was that an issue for you?

**Comment by czue** [comment]
There is an `is_attending` field on the `Guest` model [here](https://github.com/czue/django-wedding-website/blob/master/guests/models.py#L73)

You can also see how this gets set from the RSVP page ([here's an example](http://rowena-and.coryzue.com/invite/b2ad24ec5dbb4694a36ef4ab616264e0/))

**Comment by dillwishlist** [comment]
Ah okay, I misremembered that.  That works, thanks!
