### ISSUE TITLE
Settings Variables Not Affecting all Pages

### ISSUE THREAD

**Issue by dillwishlist** [czue/django-wedding-website#24]
Where are the declarations for the variables used in the email templates, etc. supposed to be defined?  I presume you stripped them out for privacy reasons, where should I place them?

Such as:
{{ support_email }}
{{ couple }}
{{ site_url }}
{{ rsvp_address }}

Thanks,
Alexander

**Comment by czue** [comment]
I think you're looking for these settings, yeah? 

https://github.com/czue/django-wedding-website/blob/master/bigday/settings.py#L129-L142

**Comment by dillwishlist** [comment]
That's what I initially assumed.  I have everything populated in there to no luck.

`\# the address your emails (save the dates/invites/etc.) will come from
DEFAULT_WEDDING_FROM_EMAIL = 'Hannah and Alexander <wedding@12345.com>'
\# the default reply-to of your emails
DEFAULT_WEDDING_REPLY_EMAIL = 'guests@12345.com'

\# when sending test emails it will use this address
DEFAULT_WEDDING_TEST_EMAIL = DEFAULT_WEDDING_FROM_EMAIL

\# This is used in a few places where the names of the couple are used
BRIDE_AND_GROOM = 'Hannah and Alexander'

\# This is used in links in save the date / invitations
WEDDING_WEBSITE_URL = 'http://12345.com'
WEDDING_CC_LIST = []  # put email addresses here if you want to cc someone on all your invitations
`

**Comment by czue** [comment]
Are you sure you edited the right file? That should be all that's required. 

If you run:
```
./manage.py shell
from django.conf import settings
print(settings.WEDDING_WEBSITE_URL)
```

Do you see your changes?

**Comment by ataylor-orcsd-org** [comment]
Yes, that works.  Some testing: on the home page, the email, etc. is replaced correctly.  On the Save the Date pages, it's not.

**Comment by czue** [comment]
> Yes, that works. Some testing: on the home page, the email, etc. is replaced correctly. On the Save the Date pages, it's not.

Ah, thanks for the clarification! Likely an oversight on my part. I'll try to fix as soon as I can (and pull requests are welcome! :smile: )

**Comment by dillwishlist** [comment]
#37 Please review this PR - should be (at least somewhat) improved.

**Comment by czue** [comment]
@dillwishlist do you think there's more to do here or shall I close this?

**Comment by dillwishlist** [comment]
@czue I think I it's safe to close, I can't find any other instances of this at the moment.
