### ISSUE TITLE
How to send emails

### ISSUE THREAD

**Issue by dillwishlist** [czue/django-wedding-website#34]
What URL or shell command should be used to send emails for save the dates or invitations?  Is there a way to test send?

**Comment by ataylor-orcsd-org** [comment]
I found this on your blog write up.  Is there any way to do this through the web interface by chance?

`python3 ./manage.py send_save_the_dates --send --mark-sent`

**Comment by czue** [comment]
That's right. Not currently possible via the web interface though probably reasonably easy to add. Out of curiosity, what's the need for doing it there?

**Comment by dillwishlist** [comment]
Gotcha.  I was searching for how to send emails and such.  If someone else wanted to press the "Send" button like my non-programmer wife, a GUI button is much easier than teaching her how to SSH into the server.  Not a big deal though.

Would you mind if I put this answer in a WiKi page?

**Comment by czue** [comment]
Ah that makes sense. Spouses! :upside_down_face:  (In my defense, my wife also codes)

Sounds great to put on a wiki page.

**Comment by dillwishlist** [comment]
Looks like I can't create the initial WiKi page, would you mind creating one and I'll fill it out?

**Comment by czue** [comment]
sure! https://github.com/czue/django-wedding-website/wiki

**Comment by dillwishlist** [comment]
Would you mind allowing contributors to edit the wiki in settings?  I'm also happy to put in wiki changes as issues/PRs if you'd prefer.  Thanks!

**Comment by czue** [comment]
done! (I think) Sorry first time using github wikis

**Comment by dillwishlist** [comment]
That worked.  Basic FAQ added, I'll add more as I come across them.  Thanks again!

**Comment by czue** [comment]
Awesome, thanks for the contribution!
