### ISSUE TITLE
To add Django variable to make it work

### ISSUE THREAD

**Issue by klorydryk** [czue/django-wedding-website#59]
To make it work, I had to add this variables in the bigday/settings.py:
ALLOWED_HOSTS = ["my_website_url"]
CSRF_TRUSTED_ORIGINS = ["my_website_url",'https://*.127.0.0.1' ] (not sure for the 'https://*.127.0.0.1' but didn't tried without it)

**Comment by czue** [comment]
thanks! happy to accept a contribution that adds these by default.

**Comment by m-terlinde** [comment]
I think this can be closed because of https://github.com/czue/django-wedding-website/pull/60.

By the way: why is there a dot in front of the IP?

**Comment by czue** [comment]
ah thanks for the heads up! also I don't know why that . was there, I removed it in https://github.com/czue/django-wedding-website/commit/ce5de39a3ee6687d800031ddf3bef0d404c7e021
