### ISSUE TITLE
Help deploying

### ISSUE THREAD

**Issue by eagleco** [czue/django-wedding-website#66]
Thanks for sharing a great project! I've gotten everything set up to our liking and working well on the development server but am struggling with getting it deployed with gunicorn. 

I can run `gunicorn bigday.wsgi --bind 0.0.0.0:8000` from the django-wedding-website folder and the server starts, but none of the static resources are found.  
![image](https://github.com/czue/django-wedding-website/assets/39813792/591b6556-bf1b-497b-ae42-1942a9048879)

If I run the same command from /django-wedding-website/bigday I get the following
![image](https://github.com/czue/django-wedding-website/assets/39813792/80bb5cc3-0879-4937-a70e-ccec81158071)

I also see the supervisor_django.conf file in /deploy/supervisor, but haven't figured out what do with it either.

Any help getting me on the right track would be great! Thanks again

**Comment by czue** [comment]
Have you set `DEBUG=False`? That will prevent Django from serving your static files.

To fix, I would recommend installing and configuring whitenoise for this: https://whitenoise.readthedocs.io/en/stable/django.html

You will also have to run `./manage.py collectstatic` every time you change anything. See the django docs for more details: https://docs.djangoproject.com/en/5.0/howto/static-files/#deployment

**Comment by eagleco** [comment]
Thanks! That did the trick.
