### ISSUE TITLE
Update to python 3 and django 2

### ISSUE THREAD

**Issue by henridwyer** [czue/django-wedding-website#7]
It would be nice to support Django 2 and python 3

**Comment by kboghdady** [comment]
I have made an update for that in my forked repo as well as a pull request in the main repo

**Comment by ulgens** [comment]
@czue What about #13 ?

**Comment by czue** [comment]
I'm just going to do some testing and will plan to merge sometime this week. thanks!

**Comment by czue** [comment]
Addressed in https://github.com/czue/django-wedding-website/pull/14/ - let me know if any issues!
